name: First CI Workflow
on: 
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  first-job:
    name: First-Job
    runs-on: windows-latest
    steps:
      - name: Initialization
        run: echo "Hellow World"
      - name: Middle
        run: echo "Continuous Testing"
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: End
        run: echo "Thank you"
  second-job:
    name: Second-Job
    runs-on: windows-latest
    steps:
      - name: Continuous Download
        run: echo "Downloading from Github"
      - name: Continous Build
        run: echo "Buildin using Maven"
      - name: Testing
        run: echo "Junit Testing"
      - name: Deploy
        run: echo "OCP or UCD"
      - name: Deliver
        run: echo "Delivered"
